# Generated by Django 3.2 on 2021-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='fname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='out_path',
            field=models.CharField(default='blank', max_length=255),
            preserve_default=False,
        ),
    ]
